init:
  functionName: HelloWorldFn
pipeline:
  trigger:
    action: aws/lambda:call
    credentials: $awsCredentials
    comments: call $functionName lambda function
    functionname: $functionName
    payload: ""
  assert:
    action: validator:assert
    comments: 'validate function output: $payload '
    actual: $trigger.Response
    expected: /Hello World/
