pipeline:
  setupDB:
    initDB:
      action: dsunit:init
      datastore: db2
      config:
        driverName: bigquery
        credentials: $gcSecrets
        parameters:
          datasetId: db2
      scripts:
       - URL: ${parent.path}/db2/schema.sql
    loadData:
      db2:
        action: dsunit:prepare
        datastore: db2
        URL:  ${parent.path}/db2/data

  deployConfig:
    action: storage:copy
    expand: true
    source:
      URL: ${appPath}/dispatcher/config/bq.json
    dest:
      URL: gs://${testBucketPrefix}_config/bq.json
      credentials: $gcSecrets

  listenOnSlack:
    listen:
      credentials: slack
      action: slack:listen
      description: listen for incoming slack messages
      channel: '#serverless'

  setupMessageBus:
    action: msg:setupResource
    resources:
      - URL: table1Topic
        type: topic
        vendor: gcp
        credentials: $gcSecrets
      - URL: table1TopicSubscription
        type: subscription
        vendor: gcp
        credentials: $gcSecrets
        config:
          topic:
            URL: /projects/${projectID}/topics/table1Topic
