pipeline:
  checkEvent:
    action: msg:pull
    timeoutMs: 10000
    source:
      URL: table1TopicSubscription
      type: subscription
      vendor: gcp
      credentials: $gcpSecrets
    count: 1
    UDF: AsMap
    expect:
      - Transformed:
          configuration:
            jobType: "QUERY"

  checkSlack:
    validate:
      action: slack:pull
      credentials: slack
      expect:
        - asset:
            Data:
              source: /table2/
              status: DONE

#  notificationInfo:
#    action: print
#    message: $AsJSON($checkEvent)