defaults:
  credentials: $gcSecrets
init:
  dataset: db2
pipeline:
  trigger:
    copyTable1:
      logging: false
      action: gcp/bigquery:query
      query: SELECT * FROM table1
      allowlargeresults: false
      defaultdataset:
        projectid: ${gcp.projectID}
        datasetid: $dataset
      destinationtable:
        projectid: ${gcp.projectID}
        datasetid: $dataset
        tableid: table1_copy
      writedisposition: WRITE_TRUNCATE
    copyTable2:
      logging: false
      action: gcp/bigquery:query
      query: SELECT * FROM table2
      allowlargeresults: false
      defaultdataset:
        projectid: ${gcp.projectID}
        datasetid: $dataset
      destinationtable:
        projectid: ${gcp.projectID}
        datasetid: $dataset
        tableid: table2_copy
      writedisposition: WRITE_TRUNCATE