defaults:
  credentials: $gcpSecrets
pipeline:
  package:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    commands:
      - cd ${appPath}/computeinfo
      - go mod vendor

  deploy:
    action: gcp/cloudfunctions:deploy
    '@name': OnChange
    entryPoint: OnChangeFn
    runtime: go111
    eventTrigger:
      eventType: google.compute.instance.stop
      resource: projects/${gcp.projectID}/zones/us-central1-f/instances/{instanceId}
    source:
      URL: ${appPath}/computeinfo
    sleepTimeMs: 20000