defaults:
  credentials: $fbSecrets
pipeline:
  package:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    commands:
      - cd ${appPath}/moderate
      - go mod vendor

  deploy:
    action: gcp/cloudfunctions:deploy
    '@name': ModeratePost
    entryPoint: ModeratePostFn
    sleepTimeMs: 10000
    runtime: go111
    eventTrigger:
      eventType: providers/cloud.firestore/eventTypes/document.write
      resource: projects/${gcp.projectID}/databases/(default)/documents/posts/{doc}
    source:
      URL: ${appPath}/moderate
