pipeline:

#  setup:
#    action: aws/lambda:setupFunction
#    credentials: aws
#    functionname: book
#    runtime:  go1.x
#    handler: main
#    code:
#      zipfile: $LoadBinary('main.zip')
#    rolename: lambda-book-executor
#    define:
#      - policyname: dynamodb-item-crud-role
#        policydocument: $Cat('privilege-policy.json')
#    attach:
#      - policyarn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  createAPI:
    action: aws/apigateway:setupRestAPI
    credentials: aws
    '@name': booktoreAPI
    resources:
      - path: /book
        methods:
          - httpMethod: ANY
            function: book
