pipeline:
  setup:
    action: msg:setupResource
    resources:
      - URL: proxySourceTopic
        type: topic
        vendor: gcp
        credentials: $gcpSecrets

      - URL: proxyTargetTopic1
        type: topic
        vendor: gcp
        credentials: $gcpSecrets

      - URL: proxySubscription1
        type: subscription
        vendor: gcp
        credentials: $gcpSecrets
        config:
          topic:
            URL: /projects/${projectID}/topics/proxyTargetTopic1

      - URL: proxyTargetTopic2
        type: topic
        vendor: gcp
        credentials: $gcpSecrets

      - URL: proxySubscription2
        type: subscription
        vendor: gcp
        credentials: $gcpSecrets
        config:
          topic:
            URL: /projects/${projectID}/topics/proxyTargetTopic2