pipeline:
  check-proxySubscription1:
    action: msg:pull
    timeoutMs: 10000
    source:
      URL: proxySubscription1
      type: subscription
      vendor: gcp
      credentials: $gcpSecrets
    count: 1
    UDF: AsMap
    expect:
      - Transformed:
          message: "this is my 1st message"
          projectID: $projectID
          source: /proxySourceTopic/

  check-proxySubscription2:
    action: msg:pull
    timeoutMs: 10000
    source:
      URL: proxySubscription2
      type: subscription
      vendor: gcp
      credentials: $gcpSecrets
    count: 1
    UDF: AsMap
    expect:
      - Transformed:
          message: "this is my 2nd message"
          projectID: $projectID
          source: /proxySourceTopic/
