pipeline:
  trigger:
    action: msg:push
    sleepTimeMs: 5000
    dest:
      URL: /projects/${projectID}/topics/proxySourceTopic
      credentials: $gcpSecrets
      vendor: gcp
    messages:
      - data:
          dest: proxyTargetTopic1
          projectID: $projectID
          message: 'this is my 1st message'
      - data:
          dest: proxyTargetTopic2
          projectID: $projectID
          message: 'this is my 2nd message'
