init:
  self.i: 0
pipeline:
  loop:
    check-content:
      action: storage:download
      source:
        URL: gs://my_e2ebucket/data/workers/0${self.i}_data.csv
        credentials: $gcSecrets
      expect: $Cat(${parent.path}/expect/0${self.i}_data.csv)
    inc:
      action: nop
      init:
        self.i: ${self.i++}
    goto:
      action: goto
      when: ${self.i} < 3
      task: loop