defaults:
  credentials: $fbSecrets
pipeline:
  package:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    commands:
      - cd ${appPath}/likes
      - go mod vendor

  deploy:
    action: gcp/cloudfunctions:deploy
    sleepTimeMs: 10000
    '@name': CountLikes
    entryPoint: CountLikesFn
    runtime: go111
    eventTrigger:
      eventType: providers/google.firebase.database/eventTypes/ref.write
      resource: projects/_/instances/${gcp.projectID}/refs/posts/{key}/likes
    source:
      URL: ${appPath}/likes
