pipeline:
  setup:
    action: msg:setupResource
    credentials: $awsCredentials
    resources:
      - URL: mye2eQueue
        type: queue
        vendor: aws
  setupLogGroup:
    action: aws/logs:setupLogGroup
    credentials: $awsCredentials
    logGroupName: /aws/lambda/MsgLogFn
    sleepTimeMs: 5000
