pipeline:
  deploy:
    action: exec:run
    comments: deploy CountLikes triggered by providers/google.firebase.database/eventTypes/ref.write
    target: $target
    sleepTimeMs: 1500
    terminators:
      - Do you want to continue
    errors:
      - ERROR
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${env.HOME}/.secret/${fbSecrets}.json
    commands:
      - cd $appPath
      - go build
      - export PATH=$PATH:${env.HOME}/google-cloud-sdk/bin/
      - gcloud config set project $fbProjectID
      - #gcloud alpha functions delete CountLikes
      - ${cmd[4].stdout}:/Do you want to continue/ ? Y
      - gcloud alpha functions deploy CountLikes --entry-point CountLikesFn --trigger-event providers/google.firebase.database/eventTypes/ref.write --trigger-resource  'projects/_/instances/${fbProjectID}/refs/posts/{key}/likes' --runtime go111





