pipeline:
  deploy:
    action: exec:run
    target: $target
    sleepTimeMs: 1500
    terminators:
      - Do you want to continue
    errors:
      - ERROR
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${env.HOME}/.secret/${gcSecrets}.json
    commands:
      - cd $appPath
      - export PATH=$PATH:${env.HOME}/google-cloud-sdk/bin/
      - gcloud config set project $projectID
      - #gcloud functions delete SplitWorkload
      - ${cmd[4].stdout}:/Do you want to continue/ ? Y
      - gcloud functions deploy SplitWorkload --entry-point SplitWorkloadFn --trigger-resource ${testBucketPrefix}_e2e001 --trigger-event google.storage.object.finalize --runtime go111



