defaults:
  credentials: $gcpSecrets
pipeline:
  package:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    checkError: true
    commands:
      - unset GOPATH
      - cd ${appPath}/split
      - go mod vendor

  deploy:
    action: gcp/cloudfunctions:deploy
    '@name': SplitWorkload
    entryPoint: SplitWorkloadFn
    runtime: go111
    public: true
    eventTrigger:
      eventType: google.storage.object.finalize
      resource: projects/_/buckets/${testBucketPrefix}_e2e001
    source:
      URL: ${appPath}/split
