init:
  testData: '_'
pipeline:
  create-bucket:
    action: storage:upload
    comments: create a bucket with dummy data
    sourceKey: testData
    dest:
      URL: gs://${testBucketPrefix}_e2e001/data
      credentials: $gcpSecrets
  cleanup:
    action: storage:remove
    comments: remove assets used in this use case
    assets:
      - URL: gs://${testBucketPrefix}_e2e001/data/master/data.csv
        credentials: $gcpSecrets
      - URL: gs://${testBucketPrefix}_e2e001/data/workers/01_data.csv
        credentials: $gcpSecrets
      - URL: gs://${testBucketPrefix}_e2e001/data/workers/02_data.csv
        credentials: $gcpSecrets
      - URL: gs://${testBucketPrefix}_e2e001/data/workers/00_data.csv
        credentials: $gcpSecrets
      - URL: gs://${testBucketPrefix}_e2e001/data
        credentials: $gcpSecrets
