pipeline:
  trigger:
    action: storage:copy
    source:
      URL: ${parent.path}/data/data.csv
    dest:
      URL: gs://${testBucketPrefix}_e2e001/data/master/data.csv
      credentials: $gcpSecrets
    sleepTimeMs: 5000