defaults:
  credentials: $gcSecrets
pipeline:
  deploy:
    action: gc/cloudfunctions:deploy
    '@name': HelloWorld
    entryPoint: HelloWorldFn
    runtime: go111
    source:
      URL: ${appPath}/hello/
