defaults:
  credentials: $fbSecrets
pipeline:
  deploy:
    action: gc/cloudfunctions:deploy
    '@name': ModeratePost
    entryPoint: ModeratePostFn
    sleepTimeMs: 1000
    runtime: go111
    eventTrigger:
      eventType: providers/cloud.firestore/eventTypes/document.write
      resource: projects/${gc.projectID}/databases/(default)/documents/posts/{doc}
    source:
      URL: ${appPath}/moderate/
