init:
  data: e2e test
pipeline:
  create-bucket:
    action: storage:upload
    comments: init bucket
    sourceKey: data
    dest:
      URL: s3://mye2e-bucket2/data.txt
      credentials: $awsCredentials
  cleanup:
    action: storage:remove
    comments: remove assets used in this use case
    assets:
      - URL: s3://mye2e-bucket2/meta/filemeta.json
        credentials: $awsCredentials
      - URL: s3://mye2e-bucket2/data.txt
        credentials: $awsCredentials
      - URL: s3://mye2e-bucket2/data/
        credentials: $awsCredentials