init:
  data: e2e test
pipeline:
  create-bucket:
    action: storage:upload
    comments: init bucket
    sourceKey: data
    dest:
      URL: s3://${testBucketPrefix}2/data.txt
      credentials: $awsCredentials
  cleanup:
    action: storage:remove
    comments: remove assets used in this use case
    assets:
      - URL: s3://${testBucketPrefix}2/meta/filemeta.json
        credentials: $awsCredentials
      - URL: s3://${testBucketPrefix}2/folder1/datafile1.csv
        credentials: $awsCredentials
      - URL: s3://${testBucketPrefix}2/folder1/datafile2.txt
        credentials: $awsCredentials