pipeline:
  loop:
    check-content:
      action: storage:download
      source:
        URL: s3://${testBucketPrefix}2/meta/filemeta.json
        credentials: $awsCredentials
      expect:
        Paths:
          's3://${testBucketPrefix}2/folder1':
            FileCount: 2
            LinesCount: 52