defaults:
  credentials: $gcpSecrets
pipeline:
  package:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    commands:
      - cd ${appPath}/query
      - go mod vendor

  deploy:
    action: gcp/cloudfunctions:deploy
    '@name': QueryBQ
    entryPoint: QueryFn
    public: true
    runtime: go111
    source:
      URL: ${appPath}/query
