pipeline:
  trigger:
    action: rest/runner:send
    URL: ${endpointURL}loginfo
    method: post
    '@request':
      region: ${awsSecrets.Region}
      URL: s3://${testBucketPrefix}/folder1/
    expect:
      Status: ok
      FileCount: 2
      LinesCount: 52