pipeline:
  undeployFunction:
    action: aws/lambda:deleteFunction
    credentials: $awsCredentials
    functionname: LoginfoFn
  undeployRestAPI:
    action: aws/apigateway:removeRestAPI
    name: loginfoAPI
