defaults:
  credentials: $gcSecrets
pipeline:
  package:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    commands:
      - cd ${appPath}/msg
      - go mod vendor

  deploy:
    action: gc/cloudfunctions:deploy
    '@name': PubSubProxy
    entryPoint: PubSubProxyFn
    runtime: go111
    eventTrigger:
      eventType: google.pubsub.topic.publish
      resource: projects/${gc.projectID}/topics/proxySourceTopic
    source:
      URL: ${appPath}/msg
