init:
  self.i: 1
pipeline:
  loop:

    setEventType:
      action: nop
      init:
        eventType: ${self.i % 3}

    trigger:
      action: msg:push
      comments: pushing message ${self.i}
      credentials: $awsCredentials
      dest:
        URL: mye2eAeroTopic
        type: topic
        vendor: aws
      messages:
        - subject: Test subject
          data: '{"EventType":$eventType, "Timestamp":"${tzTime.now}"}'
          attributes:
            id: $self.i
    inc:
      action: nop
      logging: false
      init:
        _: ${self.i++}
    until:
      action: goto
      logging: false
      task: loop
      when: $self.i <= 10
    thinkTime:
      action: nop
      comments: allow extra time for message processing
      sleepTimeMs: 2000