pipeline:
  db1-load:
    register:
      action: dsunit:register
      datastore: db1
      config:
        driverName: bigquery
        credentials: $gcSecrets
        parameters:
          datasetId: db1

