pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.11

  test:
    tag: Test
    description: '@info'
    subPath: 'cases/${index}*'
    range: 1..005
    template:
      setVars:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)

      setup:
        action: run
        comments: setup use case resources
        request: '@setup'

      deploy:
        action: run
        comments: deploy cloud function
        request: '@deploy'

      run-trigger:
        action: run
        comments: fire cloud function trigger
        request: '@trigger'
        sleepTimeMs: 500

      validate:
        when: $HasResource(${path}/test.yaml)
        action: run
        comments: validate cloud function execution
        request: '@test'

      ubdeploy:
        when: $HasResource(${path}/undeploy.yaml)
        action: run
        comments: undeploy cloud function
        request: '@undeploy'

    post-test-sleep:
      action: nop
      sleepTimeMs: 1000
      comments: sleep for extra debuging
