pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.12
  set_env:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    commands:
      - unset GOPATH
      - export GO111MODULE=on
  test:
    tag: $pathMatch
    description: '@info'
    subPath: 'cases/${index}_*'
    range: 1..010
    template:

      setVars:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)


      loadConifg:
        action: nop
        when: $HasResource(${path}/config.json)
        ':init':
          configText: $Cat('${path}/config.json')
          config: $AsMap(${configText})

        comments: load config if present


      setup:
        when: $HasResource(${path}/setup.yaml)
        action: run
        comments: setup use case resources
        request: '@setup'

      deploy:
        #when: false
        action: run
        comments: deploy cloud function
        request: '@deploy'

      run-trigger:
        action: run
        comments: fire cloud function trigger
        request: '@trigger'
        sleepTimeMs: 500

      validate:
        when: $HasResource(${path}/test.yaml)
        action: run
        comments: validate cloud function execution
        request: '@test'

#      ubdeploy:
#        when: $HasResource(${path}/undeploy.yaml)
#        action: run
#        comments: undeploy cloud function
#        request: '@undeploy'

    post-test-sleep:
      action: nop
      sleepTimeMs: 1000
      comments: sleep for extra debuging
