init:
  app: bqwt
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  appHost: $Hostname($target.URL)
  appPath: $WorkingDirectory(..)

  gcSecrets: gcp-e2e
  e2e: $secrets.e2e

  fbSecrets: fbc-e2e
  fbc: $secrets.fbc
  fbProjectID: $fbc.ProjectID

  projectID: $e2e.ProjectID
  testBucketPrefix: ${projectID}



defaults:
  app: $app
  target: $target
  buildTarget: $buildTarget
  appTarget: $appTarget
  bqCredentials: $bqCredentials
pipeline:
  setSdk:

  test:
    action: run
    request: '@regression/regression'
    tasks: '*'
