init:
  app: bqwt
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  appHost: $Hostname($target.URL)
  appPath: $WorkingDirectory(..)



  gcpSecrets: gcp-e2e
  gcp: ${secrets.$gcpSecrets}
  projectID: $gcp.ProjectID
  serviceAccount: $gcp.ClientEmail

  fbSecrets: gcp-fb-e2e
  fbc: ${secrets.gcp-fb-e2e}
  fbProjectID: $fbc.ProjectID

  awsSecrets: aws-e2e

  testBucketPrefix: ${projectID}


defaults:
  app: $app
  target: $target
  buildTarget: $buildTarget
  appTarget: $appTarget
  bqCredentials: $bqCredentials
pipeline:
  setSdk:

  test:
    action: run
    request: '@regression/regression'
    tasks: '*'
