init:
  app: bqwt
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  targetHost: $Hostname($target.URL)
  appHost: $Hostname($target.URL)
  awsCredentials: aws-e2e
  awsSecrets: ${secrets.aws-e2e}
  gcpCredentials: gcp-e2e
  appPath: $WorkingDirectory(../)
  startTimestamp: ${timestamp.now}
  testBucketPrefix: e2e$FormatTime('now','MMdd')
defaults:
  app: $app
  target: $target
  buildTarget: $buildTarget
  appTarget: $appTarget
pipeline:
  test:
    action: run
    request: '@regression/regression'
    tasks: '*'
