defaults:
  credentials: $gcpSecrets
pipeline:
  package:
    action: exec:run
    comments: vendor build for deployment speedup
    target: $target
    commands:
      - cd ${appPath}/gcetoggle
      - go mod vendor

  deploy:
    action: gcp/cloudfunctions:deploy
    '@name': ToggleVm
    entryPoint: ToggleVmFn
    runtime: go111
    public: true
    source:
      URL: ${appPath}/togglevm
    sleepTimeMs: 5000