pipeline:
  deploy:
    action: exec:run
    comments: deploy ProxyMsg tirggered by google.pubsub.topic.publish
    target: $target
    sleepTimeMs: 1500
    terminators:
     - Do you want to continue
    errors:
     - ERROR
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${env.HOME}/.secret/${gcSecrets}.json
    commands:
      - cd $appPath
      - go build
      - export PATH=$PATH:${env.HOME}/google-cloud-sdk/bin/
      - gcloud config set project $projectID
      - #gcloud alpha functions delete ProxyMsg
      - ${cmd[4].stdout}:/Do you want to continue/ ? Y
      - gcloud alpha functions deploy ProxyMsg --entry-point PubSubProxyFn --trigger-resource proxySourceTopic --trigger-event google.pubsub.topic.publish --runtime go111





